theme: jekyll-theme-architect
title: Shoira creates by coding
author: Shoira Shamsieva
email: shoira.shamsieva@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  Shoira - human, mother, software developer, Americanized Uzbek

# social links
twitter_username: shoiradev
github_username:  shoycha
show_excerpts: true # set to false to remove excerpts on the homepage
